### ISSUE TITLE
Not redirect while getting 302 response

### ISSUE THREAD

**Issue by PhamHung2601** [monsoonconsulting/magento2-hyva-ajax-add-to-cart#15]
Sometimes when submitting data, the cookie from the client is different from the server so we get a 302 redirect response.
But nothing happens.
To follow core Magento, I think if there is a redirect we should follow the redirect.
Thanks!

**Comment by callanzimmermann** [comment]
Hello @PhamHung2601, I'll have a look into this when I next get chance. I have feeling the was a reason for this., but I'll return to this with a fresh mind.
