### ISSUE TITLE
Double add to cart from upsells

### ISSUE THREAD

**Issue by web4exposure-org** [monsoonconsulting/magento2-hyva-ajax-add-to-cart#17]
**Describe the bug**
When adding a product to the cart from the cart itself (at the upsell part) the product is added twice.

**To Reproduce**
1. Add a product to the cart which has upsells
2. Go to the cart and add one of the upsells to your cart (from within the cart page)
3. The product is added twice

**Expected behavior**
The upsell product should be added just once

**Device Info (please complete the following information):**
 - Browser Firefox
 - Version 117.0.1 (64-bit)

**Magento version**
Magento ver. 2.4.6-p2

**Hyva Versions**
Hyvä Default Theme: 1.3.2
Hyvä Theme Module: 1.3.2

**Comment by callanzimmermann** [comment]
Hello @web4exposure-org, this has been fixed in 1.2.0 along with other changes.
