### ISSUE TITLE
Button disabling

### ISSUE THREAD

**Issue by Jarzebowsky** [monsoonconsulting/magento2-hyva-ajax-add-to-cart#2]
Right now you can click the button during the loader which adds the products to the cart. As this is not a major thing, we happened to have some restrictions for adding a product to the cart - that make this restrictions not working properly.

So the request would be that the button should be disabled after initial click. We have prepared overwriting of the code for our needs but I believe more people could use it. :)

**Comment by callanzimmermann** [comment]
Hello @Jarzebowsky, thanks for the bringing this up. I will look into this.

I'll get back to you soon.

**Comment by callanzimmermann** [comment]
Hello @Jarzebowsky, this has been fixed here #3. This has been merged into main and released as part of `1.1.1`.
