### ISSUE TITLE
Add Hyva Theme version constraint

### ISSUE THREAD

**Issue by nige-one** [monsoonconsulting/magento2-hyva-ajax-add-to-cart#22]
**Is your feature request related to a problem? Please describe.**
Not a real problem

**Describe the solution you'd like**
I'm still running on Hyva Theme 1.1.x being not sure if release 1.2 of this extension is compatible.
Having the (composer) information of version constrains would help and will lead to a usable installed version.

**Describe alternatives you've considered**
Checking the code each time. :(

I guess all versions are compatible down to Hyva 1.1.x for now, but this could obviously change - we are on 1.3.x now.

**Comment by callanzimmermann** [comment]
Hello @nige-one, I was discussing this internally with a colleague.

We believe as a free publicly available package we are only planning on supporting the newest versions of Magento, PHP and Hyvä.

Also, we think it's best to not require a package coming from a private packagist in a public package.
