### ISSUE TITLE
Cannot access 'data' before initialization

### ISSUE THREAD

**Issue by vchiriacmoldoweb** [monsoonconsulting/magento2-hyva-ajax-add-to-cart#25]
**Describe the bug**

There is an error now in latest version:

ReferenceError: Cannot access 'data' before initialization
    at HTMLFormElement.<anonymous> (aviation-headsets.html:4899:17)

Problem is here:
https://github.com/monsoonconsulting/magento2-hyva-ajax-add-to-cart/blob/main/view/frontend/templates/hyva/script/addtocart.phtml

```
if (data.backUrl) {
    return window.location.href = data.backUrl;
}

const data = await response.json();
```

**Comment by callanzimmermann** [comment]
Hello @vchiriacmoldoweb, thanks for spotting this so soon. This has been fixed and updated now.

Let me know if everything is fine on your side?

**Comment by vchiriacmoldoweb** [comment]
@callanzimmermann works!

**Comment by vchiriacmoldoweb** [comment]
Fixed
