### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by adamwaclawczyk** [monsoonconsulting/magento2-hyva-ajax-add-to-cart#26]
https://github.com/monsoonconsulting/magento2-hyva-ajax-add-to-cart/blob/a84311f7b51b630d96d5c5d21f3337845f1a0132/composer.json#L5

Looking through the code and testing locally(Magento version 2.4.7) it seems this module is working as expected under php8.3.

**Comment by callanzimmermann** [comment]
Hello @adamwaclawczyk, thanks for checking. Will do a quick check too and update it very soon.

**Comment by callanzimmermann** [comment]
Hello @adamwaclawczyk, updated in version [1.2.3](https://github.com/monsoonconsulting/magento2-hyva-ajax-add-to-cart/releases/tag/1.2.3), let me know if it install as expected from your side?

**Comment by adamwaclawczyk** [comment]
@callanzimmermann looks like the install went through with no issues, thanks!
